### ISSUE TITLE
travis config osx+linux + nodejs multiple versions + multiple env vars (also secured)

### ISSUE THREAD

**Issue by Ks89** [Ks89/My-MEAN-website-client#42]
I asked to travis ci community this:

I want a config file to do these builds:
- linux, nodejs 6.0,        3 env vars (blabla_1, blabla_2, blabla_3) and 2 secure vars (sec_1 and sec_2)
- linux, nodejs 6 latest, 3 env vars (blabla_1, blabla_2, blabla_3) and 2 secure vars (sec_1 and sec_2)
- linux, nodejs 7.0,        3 env vars (blabla_1, blabla_2, blabla_3) and 2 secure vars (sec_1 and sec_2)
- linux, nodejs 7 latest, 3 env vars (blabla_1, blabla_2, blabla_3) and 2 secure vars (sec_1 and sec_2)
- osx, nodejs 6.0,        3 env vars (blabla_1, blabla_5, blabla_6) and 2 secure vars (sec_1 and sec_2)
- osx, nodejs 6 latest, 3 env vars (blabla_1, blabla_5, blabla_6) and 2 secure vars (sec_1 and sec_2)
- osx, nodejs 7.0,        3 env vars (blabla_1, blabla_5, blabla_6) and 2 secure vars (sec_1 and sec_2)
- osx, nodejs 7 latest, 3 env vars (blabla_1, blabla_5, blabla_6) and 2 secure vars (sec_1 and sec_2)

PS: every build uses 3+2 env vars at the same time. I don't want to multiply builds (only 8 builds)
Also, note that blabla_1 is the same for all linux build, but could be different for the other osx builds
How can I write a .travis.yml for this configuration?

I made many tests without success.
My actual .travis.yml is:

```
language: node_js
matrix:
  include:
    - os: linux
      node_js:
        - '7'
        - '7.0'
        - '6'
        - '6.0'
      env:
        global:
          - secure: secure.var.1
          - secure: secure.var.2
        matrix:
          - blabla_1=value blabla_2=val blabla_3=val
    - os: osx
      node_js:
        - '7'
        - '7.0'
        - '6'
        - '6.0'
      env:
        global:
          - secure: secure.var.1
          - secure: secure.var.2
        matrix:
          - blabla_1=anotherval blabla_5=val blabla_6=val
sudo: required
addons:
  firefox: latest
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - bash my_script.sh
cache:
  apt: true
  bundler: true
  directories:
    - node_modules
```

Checking this .travis.yml with the official travisci validation online tool i get:
```
in addons section: unexpected key apt, dropping
in matrix.include.node_js section: does not support multiple values, dropping 7.0
in matrix.include.node_js section: does not support multiple values, dropping 6
in matrix.include.node_js section: does not support multiple values, dropping 6.0
in matrix.include section: dropping env section: unexpected pair, unexpected pair
```
